[package]
name = "chipioindustries/echo-middleware"
description = "Provides a signal that broadcasts actions that are dispatched to the Rodux store."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["wally.exe"]

[dependencies]
t = "osyrisrblx/t@3.0.0"
Llama = "chipioindustries/llama@1.2.4"
Signal = "chipioindustries/signal@1.1.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"